environment:
  file_name: null  # Set to None or the path to your Unity environment executable
  worker_id: 0
  base_port: 5004
  no_graphics: false
  seed: 12345
  time_scale: 10.0

agent:
  use_enn: true  # Set to true to use PPOAgent with ENN
  hidden_size: 128
  action_std: 0.1

training:
  num_episodes: 1000
  max_steps_per_episode: 1000
  gamma: 0.99
  lam: 0.95
  lr: 3e-4
  clip_param: 0.2
  max_grad_norm: 0.5
  entropy_coef: 0.01

enn_config:
  emotional:
    network:
      hidden_size: 64
      num_attention_heads: 4
      dropout: 0.1
  cache:
    hazard_capacity: 1000
    social_capacity: 1000
    ttl: 0.1
  safety_bounds:
    max_panic_increase: 0.3
    max_stress_increase: 0.2
    min_stamina: 0.1
